### PR TITLE
[merge] dev/frontend -> main

### PR DESCRIPTION
**Pull request by dayyyyyyyyyy**
#### PR Description:
Frontend Development 브랜치를 Main으로 머지합니다

##### Changes Included:
- [ ] Added new feature(s)
- [ ] Fixed identified bug(s)
- [ ] Updated relevant documentation

##### Screenshots (if UI changes were made):
Attach screenshots or GIFs of any visual changes. (Only for
frontend-related changes)

##### Notes for Reviewer:
Any specific instructions or points to be considered by the
reviewer.

---
#### Reviewer Checklist:
- [ ] Code is written in clean, maintainable, and idiomatic form.
- [ ] Automated test coverage is adequate.
- [ ] All existing tests pass.
- [ ] Manual testing has been performed to ensure the PR works as
expected.
- [ ] Code review comments have been addressed or clarified.

---
#### Additional Comments:
Add any other comments or information that might be useful for the
review process.

### CODE REVIEW

**Comment by 0jihunlee** [comment]
고생하셨습니다!

**Review by sgeunhi — COMMENTED** [review]
수고하셨습니다!

**Comment by tictactoeid** [comment]
수고하셨습니다! 이미 다 확인한 코드들이라 그대로 머지해도 될 것 같습니다

**Comment by HyungGeun-Cho** [comment]
수고 하셨습니다! 추후 hotfix 필요하면 dev/frontend로 바로 푸쉬할지 컨벤션만 논의하면 될 것 같습니다.

**Pull request merged**
